name: azzoa_grocery
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations :
    sdk: flutter

  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3

  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.0.6
  firebase_database: ^7.1.1
  firebase_messaging: ^10.0.2

  # flutter_facebook_login: ^3.0.0

  flutter_local_notifications: ^6.0.0
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.7

  geolocator: ^7.1.0
  # google_map_location_picker: ^4.1.7
  google_sign_in: ^5.0.4

  html: ^0.15.0
  
  json_annotation: ^4.0.1
  pinput: ^1.2.0
  shared_preferences: ^2.0.6
  sms_autofill: ^2.0.0
  sqflite: ^2.0.0+3
  
  url_launcher: ^6.0.6

  webview_flutter: ^2.0.8


  intl: ^0.17.0
  http: ^0.13.0
  
  provider: ^5.0.0
  google_maps_flutter: ^2.0.1
  image_picker: ^0.7.2
  
  path: ^1.7.0
  country_list_pick: ^1.0.1+2
  file_picker: ^3.0.1
  image_downloader: ^0.30.0
  photo_view: ^0.11.1

dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter

### Override the library to support Flutter 2.0
### Note: This will show the warning but will not impact to the app features ðŸ‘
# dependency_overrides:
#   plugin_platform_interface: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - i18n/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/roboto_regular.ttf
          weight: 400
        - asset: fonts/roboto_medium.ttf
          weight: 600
        - asset: fonts/roboto_bold.ttf
          weight: 700
